use sha1::Digest;

/// The SHA-1 hash of the empty tree object in Git, as a hex string.
fn empty_tree() -> String {
    gix::ObjectId::empty_tree(gix::hash::Kind::Sha1).to_string()
}

const QUINE_MSG_BEFORE: &str = "Quine commit\n\nHash: ";

const QUINE_MSG_AFTER: &str = "\n\n\
    This commit contains its own commit (short) hash, and was generated by\n\
    the quine tool from https://github.com/Notgnoshi/herostratus\n";

const FORTUNE_MSG_BEFORE: &str = "Fortune teller\n\nNonce: ";

fn fortune_msg_after(parent: &str) -> String {
    format!(
        "\n\n\
         This commit's hash was predicted by an ancestor commit. See:\n\
         \n\
         \x20   git log --format='%H %s' {parent}^\n\n\
         Generated by herostratus-quine from https://github.com/Notgnoshi/herostratus\n"
    )
}

/// A commit template split at the variable field boundary, enabling SHA-1 state precomputation.
///
/// The git commit object is: `commit <size>\0<content>` where content is the commit headers (tree,
/// author, committer) followed by the message.
///
/// The template is split into:
/// * `prefix` -- everything before the N-char variable field (including the git object header)
/// * `suffix` -- everything after the variable field
pub struct CommitTemplate {
    /// All bytes of the git object before the variable field.
    pub prefix: Vec<u8>,
    /// All bytes of the git object after the variable field.
    pub suffix: Vec<u8>,
    /// Number of hex characters in the variable field.
    pub prefix_len: u32,
}

impl CommitTemplate {
    /// Construct a quine commit template.
    ///
    /// The commit message will contain a `Hash: <prefix_len hex chars>` field. The template is
    /// split at the hash field so the SHA-1 prefix state can be precomputed.
    pub fn new(
        prefix_len: u32,
        parent: Option<&str>,
        author_name: &str,
        author_email: &str,
        timestamp: i64,
    ) -> CommitTemplate {
        build_template(
            prefix_len,
            parent,
            author_name,
            author_email,
            timestamp,
            QUINE_MSG_BEFORE,
            QUINE_MSG_AFTER,
        )
    }

    /// Construct a fortune-teller commit template.
    ///
    /// The commit has `parent` as its parent, and the message contains a `Nonce:` field that is
    /// iterated during the search. The goal is to find a nonce such that the resulting commit hash
    /// starts with a target prefix predicted by an ancestor.
    pub fn new_fortune_teller(
        prefix_len: u32,
        parent: &str,
        author_name: &str,
        author_email: &str,
        timestamp: i64,
    ) -> CommitTemplate {
        let msg_after = fortune_msg_after(parent);
        build_template(
            prefix_len,
            Some(parent),
            author_name,
            author_email,
            timestamp,
            FORTUNE_MSG_BEFORE,
            &msg_after,
        )
    }

    /// Build the full git object bytes for a given variable field hex string.
    ///
    /// Used for verification and output.
    pub fn build_full_object(&self, hex_field: &[u8]) -> Vec<u8> {
        let mut obj = Vec::with_capacity(self.prefix.len() + hex_field.len() + self.suffix.len());
        obj.extend_from_slice(&self.prefix);
        obj.extend_from_slice(hex_field);
        obj.extend_from_slice(&self.suffix);
        obj
    }

    /// Compute the precomputed SHA-1 hasher state from the prefix bytes.
    pub fn prefix_hasher(&self) -> sha1::Sha1 {
        let mut hasher = sha1::Sha1::new();
        hasher.update(&self.prefix);
        hasher
    }
}

fn build_template(
    prefix_len: u32,
    parent: Option<&str>,
    author_name: &str,
    author_email: &str,
    timestamp: i64,
    msg_before: &str,
    msg_after: &str,
) -> CommitTemplate {
    let placeholder: String = "0".repeat(prefix_len as usize);
    let content = format_commit_content(
        parent,
        author_name,
        author_email,
        timestamp,
        msg_before,
        &placeholder,
        msg_after,
    );
    let header = format!("commit {}\0", content.len());

    let content_before_var =
        format_content_before_var(parent, author_name, author_email, timestamp, msg_before);
    let var_offset = header.len() + content_before_var.len();

    let full_object = format!("{header}{content}");
    let prefix = full_object.as_bytes()[..var_offset].to_vec();
    let suffix = full_object.as_bytes()[var_offset + prefix_len as usize..].to_vec();

    CommitTemplate {
        prefix,
        suffix,
        prefix_len,
    }
}

/// Format the commit content before the variable field (for finding the split point).
fn format_content_before_var(
    parent: Option<&str>,
    author_name: &str,
    author_email: &str,
    timestamp: i64,
    msg_before: &str,
) -> String {
    let empty_tree = empty_tree();
    let parent_line = parent.map_or(String::new(), |h| format!("parent {h}\n"));
    format!(
        "tree {empty_tree}\n\
         {parent_line}\
         author {author_name} <{author_email}> {timestamp} +0000\n\
         committer {author_name} <{author_email}> {timestamp} +0000\n\
         \n\
         {msg_before}"
    )
}

/// Format the full commit content (without the git object header).
fn format_commit_content(
    parent: Option<&str>,
    author_name: &str,
    author_email: &str,
    timestamp: i64,
    msg_before: &str,
    var_hex: &str,
    msg_after: &str,
) -> String {
    let empty_tree = empty_tree();
    let parent_line = parent.map_or(String::new(), |h| format!("parent {h}\n"));
    format!(
        "tree {empty_tree}\n\
         {parent_line}\
         author {author_name} <{author_email}> {timestamp} +0000\n\
         committer {author_name} <{author_email}> {timestamp} +0000\n\
         \n\
         {msg_before}{var_hex}{msg_after}"
    )
}

/// Encode an integer as lowercase hex into a buffer.
///
/// Writes exactly `buf.len()` hex characters, zero-padded on the left.
pub fn encode_hex(value: u64, buf: &mut [u8]) {
    const HEX_DIGITS: &[u8; 16] = b"0123456789abcdef";
    let len = buf.len();
    for (i, byte) in buf.iter_mut().enumerate() {
        let shift = (len - 1 - i) * 4;
        *byte = HEX_DIGITS[((value >> shift) & 0xf) as usize];
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encode_hex_zero() {
        let mut buf = [0u8; 4];
        encode_hex(0, &mut buf);
        assert_eq!(&buf, b"0000");
    }

    #[test]
    fn test_encode_hex_value() {
        let mut buf = [0u8; 8];
        encode_hex(0xdeadbeef, &mut buf);
        assert_eq!(&buf, b"deadbeef");
    }

    #[test]
    fn test_encode_hex_short() {
        let mut buf = [0u8; 4];
        encode_hex(0xabcd, &mut buf);
        assert_eq!(&buf, b"abcd");
    }

    #[test]
    fn test_template_roundtrip() {
        let template = CommitTemplate::new(8, None, "Test User", "test@example.com", 1000000);
        let mut hex_buf = [0u8; 8];
        encode_hex(0x12345678, &mut hex_buf);

        let full = template.build_full_object(&hex_buf);

        // Verify the full object contains the hash field
        let full_str = std::str::from_utf8(&full).unwrap();
        assert!(full_str.contains("Hash: 12345678"));
        assert!(full_str.starts_with("commit "));
        assert!(full_str.contains(&format!("tree {}", empty_tree())));
    }

    #[test]
    fn test_template_size_is_constant() {
        // The object size must be the same regardless of which hex value we put in the hash
        // field. This is critical for the precomputation to work.
        let template = CommitTemplate::new(8, None, "Test User", "test@example.com", 1000000);
        let mut hex_a = [0u8; 8];
        let mut hex_b = [0u8; 8];
        encode_hex(0x00000000, &mut hex_a);
        encode_hex(0xffffffff, &mut hex_b);

        let obj_a = template.build_full_object(&hex_a);
        let obj_b = template.build_full_object(&hex_b);
        assert_eq!(obj_a.len(), obj_b.len());
    }

    #[test]
    fn test_prefix_hasher_produces_correct_hash() {
        let template = CommitTemplate::new(4, None, "Test", "t@t.com", 0);
        let mut hex_buf = [0u8; 4];
        encode_hex(0xabcd, &mut hex_buf);

        // Hash via precomputed prefix
        let mut hasher = template.prefix_hasher();
        hasher.update(hex_buf);
        hasher.update(&template.suffix);
        let hash_precomputed = hasher.finalize();

        // Hash the full object from scratch
        let full = template.build_full_object(&hex_buf);
        let hash_full = sha1::Sha1::digest(&full);

        assert_eq!(hash_precomputed[..], hash_full[..]);
    }

    #[test]
    fn test_fortune_teller_template() {
        let parent = "a".repeat(40);
        let template =
            CommitTemplate::new_fortune_teller(8, &parent, "Test User", "test@example.com", 1000);
        let mut hex_buf = [0u8; 8];
        encode_hex(0x12345678, &mut hex_buf);

        let full = template.build_full_object(&hex_buf);
        let full_str = std::str::from_utf8(&full).unwrap();

        assert!(full_str.contains("Nonce: 12345678"));
        assert!(full_str.contains(&format!("parent {parent}")));
        assert!(full_str.contains("Fortune teller"));
        assert!(full_str.contains("predicted by an ancestor"));
    }

    #[test]
    fn test_fortune_teller_hasher_correct() {
        let parent = "b".repeat(40);
        let template = CommitTemplate::new_fortune_teller(4, &parent, "Test", "t@t.com", 0);
        let mut hex_buf = [0u8; 4];
        encode_hex(0xabcd, &mut hex_buf);

        let mut hasher = template.prefix_hasher();
        hasher.update(hex_buf);
        hasher.update(&template.suffix);
        let hash_precomputed = hasher.finalize();

        let full = template.build_full_object(&hex_buf);
        let hash_full = sha1::Sha1::digest(&full);

        assert_eq!(hash_precomputed[..], hash_full[..]);
    }
}
