use sha1::Digest;

/// The SHA-1 hash of the empty tree object in Git, as a hex string.
fn empty_tree() -> String {
    gix::ObjectId::empty_tree(gix::hash::Kind::Sha1).to_string()
}

const MESSAGE_BEFORE_HASH: &str = "Quine commit\n\nHash: ";

const MESSAGE_AFTER_HASH: &str = "\n\n\
    This commit contains its own commit (short) hash, and was generated by\n\
    the quine tool from https://github.com/Notgnoshi/herostratus\n";

/// A commit template split at the hash field boundary, enabling SHA-1 state precomputation.
///
/// The git commit object is: `commit <size>\0<content>` where content is the commit headers (tree,
/// author, committer) followed by the message.
///
/// The template is split into:
/// * `prefix` -- everything before the N-char hash field (including the git object header)
/// * `suffix` -- everything after the hash field
pub struct CommitTemplate {
    /// All bytes of the git object before the hash field.
    pub prefix: Vec<u8>,
    /// All bytes of the git object after the hash field.
    pub suffix: Vec<u8>,
    /// Number of hex characters in the hash field.
    pub prefix_len: u32,
}

impl CommitTemplate {
    /// Construct a new commit template.
    ///
    /// The commit message will contain a `Hash: <prefix_len hex chars>` field. The template is
    /// split at the hash field so the SHA-1 prefix state can be precomputed.
    pub fn new(
        prefix_len: u32,
        author_name: &str,
        author_email: &str,
        timestamp: i64,
    ) -> CommitTemplate {
        // Build the commit content (without the git object header) using a placeholder hash.
        // The placeholder is all zeros, same length as the real hash field.
        let placeholder: String = "0".repeat(prefix_len as usize);
        let content = format_commit_content(author_name, author_email, timestamp, &placeholder);

        // The git object is: "commit <size>\0<content>"
        let header = format!("commit {}\0", content.len());

        // Find where the hash field starts within the full object.
        let content_before_hash = format_content_before_hash(author_name, author_email, timestamp);
        let hash_offset = header.len() + content_before_hash.len();

        let full_object = format!("{header}{content}");
        let prefix = full_object.as_bytes()[..hash_offset].to_vec();
        let suffix = full_object.as_bytes()[hash_offset + prefix_len as usize..].to_vec();

        CommitTemplate {
            prefix,
            suffix,
            prefix_len,
        }
    }

    /// Build the full git object bytes for a given hash hex string.
    ///
    /// Used for verification and output.
    pub fn build_full_object(&self, hash_hex: &[u8]) -> Vec<u8> {
        let mut obj = Vec::with_capacity(self.prefix.len() + hash_hex.len() + self.suffix.len());
        obj.extend_from_slice(&self.prefix);
        obj.extend_from_slice(hash_hex);
        obj.extend_from_slice(&self.suffix);
        obj
    }

    /// Compute the precomputed SHA-1 hasher state from the prefix bytes.
    pub fn prefix_hasher(&self) -> sha1::Sha1 {
        let mut hasher = sha1::Sha1::new();
        hasher.update(&self.prefix);
        hasher
    }
}

/// Format the commit content before the hash field (for finding the split point).
fn format_content_before_hash(author_name: &str, author_email: &str, timestamp: i64) -> String {
    let empty_tree = empty_tree();
    format!(
        "tree {empty_tree}\n\
         author {author_name} <{author_email}> {timestamp} +0000\n\
         committer {author_name} <{author_email}> {timestamp} +0000\n\
         \n\
         {MESSAGE_BEFORE_HASH}"
    )
}

/// Format the full commit content (without the git object header).
fn format_commit_content(
    author_name: &str,
    author_email: &str,
    timestamp: i64,
    hash_hex: &str,
) -> String {
    let empty_tree = empty_tree();
    format!(
        "tree {empty_tree}\n\
         author {author_name} <{author_email}> {timestamp} +0000\n\
         committer {author_name} <{author_email}> {timestamp} +0000\n\
         \n\
         {MESSAGE_BEFORE_HASH}{hash_hex}{MESSAGE_AFTER_HASH}"
    )
}

/// Encode an integer as lowercase hex into a buffer.
///
/// Writes exactly `buf.len()` hex characters, zero-padded on the left.
pub fn encode_hex(value: u64, buf: &mut [u8]) {
    const HEX_DIGITS: &[u8; 16] = b"0123456789abcdef";
    let len = buf.len();
    for (i, byte) in buf.iter_mut().enumerate() {
        let shift = (len - 1 - i) * 4;
        *byte = HEX_DIGITS[((value >> shift) & 0xf) as usize];
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encode_hex_zero() {
        let mut buf = [0u8; 4];
        encode_hex(0, &mut buf);
        assert_eq!(&buf, b"0000");
    }

    #[test]
    fn test_encode_hex_value() {
        let mut buf = [0u8; 8];
        encode_hex(0xdeadbeef, &mut buf);
        assert_eq!(&buf, b"deadbeef");
    }

    #[test]
    fn test_encode_hex_short() {
        let mut buf = [0u8; 4];
        encode_hex(0xabcd, &mut buf);
        assert_eq!(&buf, b"abcd");
    }

    #[test]
    fn test_template_roundtrip() {
        let template = CommitTemplate::new(8, "Test User", "test@example.com", 1000000);
        let mut hex_buf = [0u8; 8];
        encode_hex(0x12345678, &mut hex_buf);

        let full = template.build_full_object(&hex_buf);

        // Verify the full object contains the hash field
        let full_str = std::str::from_utf8(&full).unwrap();
        assert!(full_str.contains("Hash: 12345678"));
        assert!(full_str.starts_with("commit "));
        assert!(full_str.contains(&format!("tree {}", empty_tree())));
    }

    #[test]
    fn test_template_size_is_constant() {
        // The object size must be the same regardless of which hex value we put in the hash
        // field. This is critical for the precomputation to work.
        let template = CommitTemplate::new(8, "Test User", "test@example.com", 1000000);
        let mut hex_a = [0u8; 8];
        let mut hex_b = [0u8; 8];
        encode_hex(0x00000000, &mut hex_a);
        encode_hex(0xffffffff, &mut hex_b);

        let obj_a = template.build_full_object(&hex_a);
        let obj_b = template.build_full_object(&hex_b);
        assert_eq!(obj_a.len(), obj_b.len());
    }

    #[test]
    fn test_prefix_hasher_produces_correct_hash() {
        let template = CommitTemplate::new(4, "Test", "t@t.com", 0);
        let mut hex_buf = [0u8; 4];
        encode_hex(0xabcd, &mut hex_buf);

        // Hash via precomputed prefix
        let mut hasher = template.prefix_hasher();
        hasher.update(hex_buf);
        hasher.update(&template.suffix);
        let hash_precomputed = hasher.finalize();

        // Hash the full object from scratch
        let full = template.build_full_object(&hex_buf);
        let hash_full = sha1::Sha1::digest(&full);

        assert_eq!(hash_precomputed[..], hash_full[..]);
    }
}
