name: Lint
on: push
env:
    RUSTFLAGS: -D warnings
    CARGO_TERM_COLOR: always

jobs:
    gitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                # PRs (hopefully??!) won't have more than 20 commits
                fetch-depth: 20
            - name: Install gitlint
              run: python -m pip install gitlint
            - name: Run gitlint
              env:
                # Don't use github.event.pull_request.base-sha, because that requires a workflow
                # event of 'pull_request' which precludes running this workflow on 'main'.
                GITLINT_COMMIT_RANGE: "origin/main..HEAD"
              run: |
                echo "GITLINT_COMMIT_RANGE=$GITLINT_COMMIT_RANGE"
                git fetch origin main:main
                git log --color=always --graph --decorate --oneline "$GITLINT_COMMIT_RANGE"
                gitlint \
                    --ignore-stdin \
                    --config .github/gitlint/gitlint.ini \
                    --extra-path .github/gitlint/ \
                    --commits "$GITLINT_COMMIT_RANGE"

    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
                components: rustfmt
            - name: Setup Rust cache
              uses: swatinem/rust-cache@v2
            - name: Run rustfmt
              run: cargo fmt -- --check --config group_imports=StdExternalCrate,imports_granularity=Module

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
                components: clippy
            - name: Setup Rust cache
              uses: swatinem/rust-cache@v2
            - name: Build
              run: cargo build --release --all-targets
            - name: Clippy
              run: cargo clippy --no-deps --release --all-targets

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: stable
            - name: Setup Rust cache
              uses: swatinem/rust-cache@v2
            - name: Test
              run: |
                git fetch
                cargo test --release --all-targets
                cargo test --release --all-targets -- --ignored
